### PR TITLE
Week 11: Application Layers

### PR DESCRIPTION
**Pull request by CloudeWu**
* Simplify the skill processing workflow
 * Change requests into post request
 * Add `Entity::SalaryDistribution` to handle salary processing
 * Use PageObject to enhance acceptance test quality
 * Create FormObjects to validate user inputs
 * Create `AnalyzeSkill` service to improve readability of app.rb

Note that:
 * cassettes are updated
 * development database may need to be wiped

### CODE REVIEW

**Comment by nlpersimon** [comment]
The reek has 4 warnings on my machine about code like [this](https://github.com/KeroKnows/s-killer/pull/27/files#diff-39ac488677f95116a973db9554d998fbd4d05ac478317deee7d13a2ffb7a590aR40).

**Comment by CloudeWu** [comment]
> The reek has 4 warnings on my machine about code like [this](https://github.com/KeroKnows/s-killer/pull/27/files#diff-39ac488677f95116a973db9554d998fbd4d05ac478317deee7d13a2ffb7a590aR40).

Ah yeah. I forgot to add this into my description. 
I am not sure how to deal with that because reek suggests us write `rescue e` as `rescue error`, but rubocop (and the community) prefers `rescue e`. There's a conflict here and I am not able to solve them at the same time.

What do you think we should do? Leave it like this or meet reek's requirement?

**Comment by nlpersimon** [comment]
> > The reek has 4 warnings on my machine about code like [this](https://github.com/KeroKnows/s-killer/pull/27/files#diff-39ac488677f95116a973db9554d998fbd4d05ac478317deee7d13a2ffb7a590aR40).
> 
> Ah yeah. I forgot to add this into my description. I am not sure how to deal with that because reek suggests us write `rescue e` as `rescue error`, but rubocop (and the community) prefers `rescue e`. There's a conflict here and I am not able to solve them at the same time.
> 
> What do you think we should do? Leave it like this or meet reek's requirement?
> 
> [edit] A discussion I found is this [issue](https://github.com/troessner/reek/issues/1136).


`rescue e` makes sense to me. Perhaps we could use a comment like `:reek:UncommunicativeVariableName` to disable the warnings.

**Comment by CloudeWu** [comment]
> Perhaps we could use a comment like `:reek:UncommunicativeVariableName` to disable the warnings.

Fixed :)

**Review by tienyulin — COMMENTED** [review]
Reviewed, nice!

**Pull request merged**
