### PR TITLE
Refactor workflow

### PR DESCRIPTION
**Pull request by nlpersimon**
The commits are almost for refactoring:

- simplify the procedure in details route for extracting information and mapping to view object
- refactor the acceptance tests using page objects
- move the logic of estimating salary distribution from view objects to a distinct entity class `SalaryDistribution`

**(update) Please run the command `rake spec_accept` to perform the acceptance tests. Also, the secrets_example.yml was modified. Please modify your secrets.yml before you run any tests.**

### CODE REVIEW

**Comment by CloudeWu** [comment]
I suspect if the database is used. I have to wait like 1 minute or so every time I submit the same query. 
```
::1 - - [27/Nov/2021:17:25:22 +0800] "GET /details?query=backend HTTP/1.1" 200 60448 71.6521
::1 - - [27/Nov/2021:17:26:30 +0800] "GET /details?query=backend HTTP/1.1" 200 60448 63.0106
::1 - - [27/Nov/2021:17:27:09 +0800] "GET /?query=backend HTTP/1.1" 200 1638 0.0134
::1 - - [27/Nov/2021:17:28:11 +0800] "GET /details?query=backend HTTP/1.1" 200 60448 60.1998
::1 - - [27/Nov/2021:17:28:20 +0800] "GET /details?query=backend HTTP/1.1" 200 60448 61.8702
```

**Comment by nlpersimon** [comment]
> I suspect if the database is used. I have to wait like 1 minute or so every time I submit the same query.
> 
> ```
> ::1 - - [27/Nov/2021:17:25:22 +0800] "GET /details?query=backend HTTP/1.1" 200 60448 71.6521
> ::1 - - [27/Nov/2021:17:26:30 +0800] "GET /details?query=backend HTTP/1.1" 200 60448 63.0106
> ::1 - - [27/Nov/2021:17:27:09 +0800] "GET /?query=backend HTTP/1.1" 200 1638 0.0134
> ::1 - - [27/Nov/2021:17:28:11 +0800] "GET /details?query=backend HTTP/1.1" 200 60448 60.1998
> ::1 - - [27/Nov/2021:17:28:20 +0800] "GET /details?query=backend HTTP/1.1" 200 60448 61.8702
> ```
> 
> By the way, the acceptance tests don't pass on my machine. Looking into it now.

The latency probably results from the [currency exchanging](https://github.com/KeroKnows/s-killer/pull/26/files#diff-bb037d07fd47f6ba52984bdb1438f0cd9b757a04674265fa8fdca212f4ab5b49R12)

**Comment by CloudeWu** [comment]
> the secrets_example.yml was modified, this might be the reason why the acceptance tests don't pass?

Got it. The tests pass now, after I added the APP_HOST property.

> The latency probably results from the currency exchanging

This makes sense. Then should we still exchange the currency in real-time? (maybe we can discuss it next week)

**Comment by nlpersimon** [comment]
> > the secrets_example.yml was modified, this might be the reason why the acceptance tests don't pass?
> 
> Got it. The tests pass now, after I added the APP_HOST property.
> 
> > The latency probably results from the currency exchanging
> 
> This makes sense. Then should we still exchange the currency in real-time? (maybe we can discuss it next week)
Let's discuss about the issue next week. I think we can exchange the currency before store data to the database.

**Pull request merged**
